services:
  nanolog:
    build:
      context: .
      args:
        FLAG2: "DCI{N4n0L0g_Opt1on_fn_F0rg3d_UdSHxt7n4eM95H4i}"
    restart: unless-stopped
    ports:
      - "1337:1337"
    environment:
      - FLAG1=DCI{N4n0L0g_Adm1n_Byp4ss_b14b12bbcc2b}
    # pid: host   # Container escape vulnerability | Waiting on greenlight from infrastructure team
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
